#!/usr/bin/env bash
# Configures ufw to block all incoming traffic except SSH, HTTP, and HTTPS
apt-get update -y
apt-get install -y ufw

ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp

ufw default deny incoming
ufw default allow outgoing

ufw --force enable
