#!/usr/bin/env bash
# Installing Nginx on Ubuntu
# Nginx is listening on port 80
# The GET request should return a page containing "Holberton School"

sudo apt-get update -y
sudo apt-get install nginx -y

sudo mkdir -p /var/www/html
echo "Holberton School" | sudo tee /var/www/html/index.html

sudo nginx -s reload 2>/dev/null || sudo /usr/sbin/nginx
