#!/usr/bin/env bash
# Installs and configures nginx to serve "Holberton School" on port 80
apt-get update -y
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx start
